package com.example.trello.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import javax.persistence.*;
import java.util.Date;


//id bigint generated by default as identity primary key,
//        title varchar(255),
//        done bool,
//        card_id bigint not null,
//        created timestamp,
//        foreign key (card_id) references cards(id) on delete cascade
@Entity
@Table(name = "checks")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class CheckEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column
    private String title;

    @Column
    private boolean done;

    @Temporal(TemporalType.TIMESTAMP)
    @Column
    @CreationTimestamp
    private Date created;

    @JsonIgnore
    @ManyToOne
    private CardEntity card;
}
