package com.example.trello.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import javax.persistence.*;
import java.util.Date;

//id bigint generated by default as identity primary key,
//        content text,
//        created timestamp,
//        user_id bigint not null,
//        foreign key (user_id) references users(id)


// if I was a table I would have a foreign key to yours that is one to one
// because the key column would be named "my_love" and this love is you Sanechka
@Entity
@Table(name = "comments")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class CommentEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column
    private String content;

    @Temporal(TemporalType.TIMESTAMP)
    @Column
    @CreationTimestamp
    private Date created;

    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    private CardEntity card;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id")
    private UserEntity user;
}
