package com.example.trello.models;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import javax.persistence.*;
import java.util.*;

//id bigint generated by default as identity primary key,
//        name varchar(255),
//        created timestamp
@Entity
@Table(name = "desks")
@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
public class DeskEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToMany(cascade = { CascadeType.ALL })
    @JoinTable(
            name = "desks_users",
            joinColumns = { @JoinColumn(name = "desk_id") },
            inverseJoinColumns = { @JoinColumn(name = "user_id") }
    )
    private Set<UserEntity> users = new HashSet<>();

    @Column
    private String name;

    @Temporal(TemporalType.TIMESTAMP)
    @Column
    @CreationTimestamp
    private Date created;
}
