CREATE TABLE IF NOT EXISTS confirmations(
    id bigint generated by default as identity primary key,
    link text,
    created timestamp,
    user_id bigint not null,
    foreign key (user_id) references users(id) on delete cascade
);
