CREATE TABLE IF NOT EXISTS users(
    id bigint generated by default as identity primary key ,
    created timestamp,
    updated timestamp,
    email varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255),
    username varchar(255)
);

CREATE UNIQUE INDEX user_email_idx on users(email);
CREATE UNIQUE INDEX user_username_idx on users(username);

CREATE TABLE IF NOT EXISTS roles(
    id bigint generated by default as identity primary key,
    created timestamp,
    updated timestamp,
    name varchar(255)
);

CREATE UNIQUE INDEX role_name_idx on roles(name);

CREATE TABLE IF NOT EXISTS users_roles(
   user_id bigint not null,
   role_id bigint not null,
   foreign key (user_id) references users(id),
   foreign key (role_id) references roles(id)
);

CREATE TABLE IF NOT EXISTS desks(
    id bigint generated by default as identity primary key,
    name varchar(255),
    created timestamp
);

CREATE TABLE IF NOT EXISTS desks_users(
  user_id bigint not null,
  desk_id bigint not null,
  foreign key (user_id) references users(id),
  foreign key (desk_id) references desks(id)
);

CREATE TABLE IF NOT EXISTS invites(
  id bigint generated by default as identity primary key,
  code varchar(255),
  user_id bigint not null,
  desk_id bigint not null,
  foreign key (user_id) references users(id),
  foreign key (desk_id) references desks(id)
);

CREATE TABLE IF NOT EXISTS lists(
    id bigint generated by default as identity primary key,
    title varchar(255),
    created timestamp,
    desk_id bigint not null,
    foreign key (desk_id) references desks(id) on delete cascade
);

CREATE TABLE IF NOT EXISTS cards(
    id bigint generated by default as identity primary key,
    title varchar(255),
    archived bool,
    description text,
    deadline timestamp,
    created timestamp,
    list_id bigint not null,
    foreign key (list_id) references lists(id) on delete cascade
);

CREATE TABLE IF NOT EXISTS comments(
   id bigint generated by default as identity primary key,
   content text,
   created timestamp,
   user_id bigint not null,
   card_id bigint not null,
   foreign key (user_id) references users(id) on delete cascade,
   foreign key (card_id) references cards(id) on delete cascade
);

CREATE TABLE IF NOT EXISTS checks(
    id bigint generated by default as identity primary key,
    title varchar(255),
    done bool,
    card_id bigint not null,
    created timestamp,
    foreign key (card_id) references cards(id) on delete cascade
);
