version: '3.4'

services:
  database:
    image: postgres
#    volumes:
#      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - "1337:5432"
    environment:
      POSTGRES_DB: "trello"
